name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js and Install Dependencies
      uses: ./.github/actions/setup

    - name: Build and Validate
      uses: ./.github/actions/build-and-validate

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ (github.event_name == 'push' && (github.ref_name == 'main' || github.ref == 'refs/heads/main')) && 'production' || 'development' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - run: echo "${{ (github.event_name == 'push' && (github.ref_name == 'main' || github.ref == 'refs/heads/main')) && 'production' || 'development' }}"

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
